### ISSUE TITLE
plantuml-preview ImageMagick error "xmlParseCharRef: invalid xmlChar value"

### ISSUE THREAD

**Issue by transducer** [skuro/plantuml-mode#107]
Hi Carlo,

When I use `plantuml-preview` I get the following error:

```
ImageMagick error: xmlParseCharRef: invalid xmlChar value 1
 `No such file or directory` @ error/svg.c/SVGError/2984
```

No image is generated:

<img src="https://i.imgur.com/El3iBcv.png" alt="Screenshot" width="50%"/>

Generating the image via `java -jar ~/plantuml.jar overview.pum` works fine.

I installed the latest version of ImageMagick via `brew update && brew upgrade`, but the error persists.

## Details
- plantuml-mode version: plantuml-mode-20190531.853, (via Spacemacs 0.200.13)
- OS: macOS Mojave 10.14.5
- Emacs version: GNU Emacs 26.2
- ImageMagick version: ImageMagick 7.0.8-59 Q16 x86_64 2019-08-05

Kind regards,
Erwin

**Comment by scottdw** [comment]
I suspect this is due to the SVG output including java warnings about illegal reflective access. To test this specify SVG output when running the java command:
```
java -jar ~/plantuml.jar -tsvg overview.pum
```

If a warning is being printed it can be silenced by adding:
``` elisp
(add-to-list 'plantuml-java-args "--illegal-access=deny")
```
to your emacs config.

(Offending line in plantuml: https://github.com/plantuml/plantuml/blob/18b688210f74570831a9218a0d6fa54d5d72380b/src/net/sourceforge/plantuml/svg/SvgGraphics.java#L532 - by denying access to directly loading that classname an exception is thrown and the default TransformerFactory is loaded. This appears to be the requested class anyway.)

**Comment by skuro** [comment]
@scottdw tip sounds quite promising. I tried to reproduce the issue on the latest stable release (`v1.3.1`) and I cannot actually see the error. You *might* also try to 

Note to self: update the issue template to include the following extra details

- value of `plantuml-exec-mode`
- value of `plantuml-output-type`

**Comment by transducer** [comment]
Thanks for the help! 

With a simpler example the rendering does work in both SVG and PNG. Example that does not work:

```
@startuml
node Resource as resource
note right of resource : foo
@enduml
```

Removing the `note right of ...` part makes it work with `plantuml-preview`.

The example with note does work when using `java -jar ~/plantuml.jar overview.pum` though.

**Comment by skuro** [comment]
@transducer I manually tried your version together with and without @scottdw suggestions and I can confirm that it fixes your issues. While you can patch your system as @scottdw suggested, a new release will be cut from MELPA unstable soon
