### ISSUE TITLE
Graceful failure when `puml-plantuml-jar-path` is not properly set

### ISSUE THREAD

**Issue by skuro** [skuro/plantuml-mode#22]
Provide a useful error message when the PlantUML JAR cannot be located at the `puml-plantuml-jar-path`

----

A wrong path for `puml-plantuml-jar-path` is the most common mistake that can be done by the user when using `puml-mode`. Things like [typos in the path](#21) might be quite hard to spot and lead to a very confused user.

**Comment by Balooga** [comment]
Can this be flagged as an "info" warning but continue to allow puml mode to function?

https://github.com/skuro/puml-mode/blob/master/puml-mode.el#L111

I have to use the following workaround when using the Cygwin version of Emacs in Windows due to the fact that java.exe requires msdos style pathnames, but Cygwin-Emacs uses the unix style pathnames.

````
(setq-default puml-plantuml-jar-path 
              (concat
               "`cygpath -m "
               (expand-file-name "plantuml.jar" dotfiles/site-dir)
               "`"))
````
Which will create a path similar to the following to allow java.exe to find plantuml.jar, but this of course fails in Emacs.

````
`cygpath -m /cygdrive/c/Users/Blah/.emacs/site/plantuml.jar`
````

**Comment by skuro** [comment]
As of `plantuml-mode v1.0.0` it's now encouraged to [use a wrapper script](https://github.com/skuro/plantuml-mode/issues/26#issuecomment-253801801) to do the things you are trying to achieve.

I honestly don't find much value in a graceful degradation approach: the main features of `plantuml-mode` is preview and syntax highlight, both of which require a valid `plantuml.jar`.
