### ISSUE TITLE
hide the plantuml logo on startup

### ISSUE THREAD

**Issue by adl** [skuro/plantuml-mode#33]
Currently, every time you start `plantuml-mode` and every time you preview some diagram, `plantuml` is executed and overlays some logo on the screen during its execution.  This logo is very annoying to me, and I do not want to see it.

One way to prevent it is to replace `java -jar plantuml.jar` by `java -Djava.awt.headless=true -jar plantuml.jar`.  However I cannot just do `(setq plantuml-java-command "java -Djava.awt.headless=true")` because that variable is passed straight to `start-process` which will complain that there is no such a program.  So the flags need to be separate.

Would it be reasonable to introduce
```
(defvar plantuml-java-flags "-Djava.awt.headless=true" "Extra flags to pass to java")
```
and use it in the two places where `plantuml-java-command` is used?

**Comment by abcdec** [comment]
Can we just turn it off by default?  For daily plantuml edit work and with many uml fragment files to process, this splash is just annoying, which is not needed once environment is setup.  I was thinking to propose a nosplash option for this (example implementation in https://github.com/abcdec/plantuml-mode/blob/nosplash/plantuml-mode.el.)

Introducing a generic java flag is probably still a good idea, but in such case I'd say please make it a list of string, not just string, since otherwise call-process/start-process cannot use it in case users want to specify multiple options.  A string with space delimited options will create issue similar to plantuml-java-command case that you pointed out. For windows support especially use of call-process/start-process would be somehow preferred...

**Comment by adl** [comment]
@abcdec: I'm all for turning it off by default.  IMHO such splash screens are totally inappropriate for command-line tools.  That's why I suggested to make this the default value for `plantuml-java-flags`.  Good point on making this a list, though.

I don't think using `-splash:no` and `-splash:yes` as in your linked implementation is correct. The `java` man page states:
```
       -splash:imgname
           Shows the splash screen with the image specified by imgname. 
           For example, to show the splash.gif file from the images
           directory when starting your application, use the following option:

               -splash:images/splash.gif
```
Therefore using `-splash:no` only works if there is no image file called `no` in the current directory, and `-splash:yes` will just attempt to display the file `yes`.

**Comment by skuro** [comment]
I agree with both keeping the execution headless[1] by default and to have a common customizable source for command line arguments. Please checkout the [feature/nosplash](https://github.com/skuro/plantuml-mode/tree/feature/nosplash) branch and let me know if it works for you as well (in the past, anything that fiddled with command line arguments proved shady especially if you factor in Windows support). 

Also, if you happen to have have some elisp background please code-review my changes, as I'm still a white belt in this field.

[1] I have one concern, that PlantUML authors wouldn't approve of hiding their splash. But I have found no evidence to substantiate such a statement. For future reference: dear @plantuml, feel free to comment and I'll be happy to consider reverting this change.

**Comment by skuro** [comment]
After your code reviews, I have already merged all the code in master. `v1.1.0` should reach MELPA soon.
