### ISSUE TITLE
[Question] org-babel not exec plantuml

### ISSUE THREAD

**Issue by bimawa** [skuro/plantuml-mode#53]
Guys help me pls with a problem. i'm try using planuml-mode in org-babel and can't execute next code  from example% 

```
#+begin_src plantuml :file tryout.png
  Alice -> Bob: synchronous call
  Alice ->> Bob: asynchronous call
#+end_src

#+results:
file:tryout.png
``` 
And receive `Evaluation of this plantuml code block is disabled.` What i do wrong? 
And what is strange i can't find function `org-babel-execute:plantuml ` in emacs  (described [here](http://orgmode.org/w/?p=org-mode.git;a=blob_plain;f=lisp/ob-plantuml.el;hb=HEAD))

**Comment by skuro** [comment]
Your description suggests that you might be using the [default org-babel integration](http://eschulte.github.io/babel-dev/DONE-integrate-plantuml-support.html) with plantuml instead of `plantuml-mode`, which are alternative implementations of the same idea with `plantuml-mode` being a bigger project. Did you follow the documentation on the README on this repository? Did you by chance apply the configuration described in the previous link? If you did both, chances are one is overriding the other as the code block tag.

**Comment by skuro** [comment]
Closing for now, please open a new issue if you continue to have a misbehaving `org-babel` integration.
