### ISSUE TITLE
Package missing from Melpa

### ISSUE THREAD

**Issue by debajit** [skuro/plantuml-mode#61]
# Summary

This package is missing from melpa. Can you publish this please? It will make installations really easy.

**Comment by skuro** [comment]
`plantuml-mode` was already deployed on MELPA, but it was momentarily purged [due to licensing issues](https://github.com/skuro/plantuml-mode/issues/60). As of release `v1.2.4` the license has been moved to GPLv3+ and `plantuml-mode` was already [reintroduced into MELPA](https://github.com/melpa/melpa/pull/4946). I already checked that both [unstable](https://melpa.org/#/plantuml-mode) and [stable](https://stable.melpa.org/#/plantuml-mode) versions of the package are again available.
