### ISSUE TITLE
Unable to change any colors

### ISSUE THREAD

**Issue by clearmisp** [skuro/plantuml-mode#62]
I'm unable to change any colors in the generated sequence diagram. If I have the following in a .plantuml buffer and do C-c C-c I get a generated sequence diagram in default colors:

`skinparam BackgroundColor DarkGrey 

c_ect_down_handler -> Track : handleConnectionDown
Track -> Agent : handle_connection_down
Agent -> Track : get_state
`
Using `skinparam monochrome true`  and `skinparam handwritten true` does work.

I use a dark theme and want to change the colors to match the theme but nothing I've tried has any effect on the rendered image. I'm also unable to change any fonts.

**Comment by skuro** [comment]
Looking at [your fix](https://github.com/ReneSchmelzer/plantuml-mode/commit/8ebb5f690c66cc27920975ab99d6922bb47b1836) I assume this is not a `plantuml-mode` issue. Closing.

**Comment by Digicrat** [comment]
This is an old issue, but, since it's the top result when searching for an answer to color issues in plantuml-mode, the correct/current solution to this issue is to put the following in your .emacs file:

`  (setq plantuml-output-type "png")`

For reference, I did not experience this issue on my Mac running Aquamacs where, strangely, the svg image type seems not to be supported.
