### ISSUE TITLE
Remove the bin/plantuml.jar from the project.

### ISSUE THREAD

**Issue by kaiwk** [skuro/plantuml-mode#73]
# Summary

It's might not be a good idea to put `plantuml.jar` in the package.
Some reasons for that:

1. Every time `plantuml.jar` updates, this package needs update.
2. Some emacs package managers use `git` to get the package, including jar makes `git clone` take a long time. 

We should better just give a download link in `README.md`, that will be convenient enough for users.

http://plantuml.com/download

**Comment by skuro** [comment]
The `jar` file shipped in this repository is only used for test purposes and should never get into anyone's Emacs let alone used by actual users. Getting rid of it requires changing CI so that it gets downloaded at build time, which I do regard as an improvement.

I'll also update the `README` with the link, makes sense indeed.
