### ISSUE TITLE
keyword font lock in node label

### ISSUE THREAD

**Issue by timmli** [skuro/plantuml-mode#84]
Words appearing in node labels may be highlighted as keywords even though they don't take effect. 

![plantuml-fontlock](https://user-images.githubusercontent.com/4593031/49931449-2b1bf680-fec7-11e8-8ae6-89a8c1089975.PNG)

**Comment by skuro** [comment]
that's a tricky one to support, since PlantUML uses the `<-` character sequence as having different meaning depending on the different diagram kind. Besides, we still have quite a weak syntax-aware highlighting capabilities for the time being. I'll keep the issue open, but don't expect much of a quick fix to come in anytime soon.
